name: tropimotos_app
description: "Aplicacion de transporte en motos para Bolivia"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  flutter_secure_storage: ^9.2.2
  provider: ^6.1.2
  go_router: ^14.6.2
  geolocator: ^13.0.2
  shared_preferences: ^2.3.2
  flutter_map: ^8.3.0
  latlong2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
